Updating Coding Challenge Readme
getkwara/recruitment-kata-fe pull request #2
Opened 2021-09-14 08:17 UTC by aioimo

CH: https://app.shortcut.com/getkwara/story/26196/improve-frontend-code-challenge

2021-09-14 12:17 UTC, fadiktekin requested changes

2021-09-14 12:17 UTC, fadiktekin commented on README.md
> +The current repo is the the Slider in its current form, developed previously by a junior dev.
```suggestion
The current repo is the Slider in its current form, developed previously by a junior dev.
```

2021-09-14 12:17 UTC, fadiktekin commented on README.md
>  If everything goes smoothly you will have a local version of the slider visibile on http://localhost:3000/
...version of the slider visibile 

should be 

...version of the slider **visible**

2021-09-14 12:17 UTC, fadiktekin commented on README.md
> +You may notice the server is sporadically unstable, returning an error. We ask that you handle the errors in a reasonable way. Unfortunately, the UX designer is out sick, so the implementation is in
Haha I love this "the UX designer is out sick"

2021-09-14 15:39 UTC, nobitagit commented
LGTM

2021-09-14 15:46 UTC, nobitagit commented on server/index.js
> +// PLEASE DO NOT CHANGE THIS FILE
👍

2021-09-16 15:06 UTC, fadiktekin approved these changes

2021-09-16 15:06 UTC, merged